---
- hosts: all
  gather_facts: false

  vars:
    service_account: ansible
    vault_passphrase: "foobar" # it should be provided by outside

  tasks:
  - name: generate a password
    set_fact:
      service_account_password: "{{ lookup('password', '/dev/null', seed=inventory_hostname) | vault(vault_passphrase) }}"
      cacheable: true

  - name: change a password for a service account
    user:
      name: "{{ service_account }}"
      state: present
      password: "{{ service_account_password | unvault(vault_passphrase) | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    become: true

