---
- hosts: all
  gather_facts: true
  remote_user: ansible

  vars:
    #ansible_user: ansible
    #ansible_password: "{{ service_account_password }}"

  task:
    - name: run something
      command: echo 'hello'
