---
- hosts: all
  gather_facts: true

  vars:
    vault_passphrase: "foobar" # it should be provided by outside
    ansible_user: ansible
    ansible_password: "{{ service_account_password | unvault(vault_passphrase) }}"

  tasks:
    - name: run something
      command: hostname 
